name: "Close stale issues and PRs"

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at 00:00 AM
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v10
        with:
          stale-issue-message: "This issue is stale because it has been open 30 days with no activity."
          stale-pr-message: "This PR is stale because it has been open 30 days with no activity."
          close-issue-message: "This issue was closed because it has been stalled for 7 days with no activity."
          close-pr-message: "This PR was closed because it has been stalled for 7 days with no activity."
          days-before-stale: 30
          days-before-close: 7
          exempt-issue-labels: "keep-open"
          exempt-pr-labels: "keep-open"
          stale-issue-label: "stale"
          stale-pr-label: "stale"
