name: integration tests

on: #add your hook triggers in the array [push, pull, merge]
  pull_request: # Trigger only on pull request events
    branches:
      - dev
      - main
  workflow_dispatch: # Allow manual triggering of the workflow

env:
  token: ${{ secrets.GITHUB_TOKEN }} # Use the built-in GITHUB_TOKEN for authentication
  UV_INDEX_VITO_ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
  UV_INDEX_VITO_ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
  AWS_ENDPOINT_URL: https://s3.waw4-1.cloudferro.com/
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          version: "0.8.x"
          python-version: "3.11"

      - name: Run tests
        run: uv run pytest tests -m "not terrascope"
