# Uploads veg-workflows wheel to vito private artifactory

name: Publish Wheel
on:
  release:
    types: [published]

  workflow_dispatch:  # Allow manual triggering of the workflow (optional)

permissions:
  contents: read

env:
  token: ${{ secrets.GITHUB_TOKEN }}  # Use the built-in GITHUB_TOKEN for authentication
  UV_INDEX_VITO_ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
  UV_INDEX_VITO_ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          version: "0.8.x"
          python-version: "3.11"
          enable-cache: true

      - name: Build release distributions
        run: |
          uv build --wheel

      - name: Upload distributions
        uses: actions/upload-artifact@v6
        with:
          name: release-dists
          path: dist/

  private-artifactory-publish:
    environment: private-artifactory
    env:
      UV_PUBLISH_USERNAME: ${{ secrets.UV_PUBLISH_USERNAME }}
      UV_PUBLISH_PASSWORD: ${{ secrets.UV_PUBLISH_PASSWORD }}
      UV_PUBLISH_URL: ${{ vars.UV_PUBLISH_URL }}
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest
    needs:
      - release-build

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v7
        with:
          name: release-dists
          path: dist/

      - name: Publish whl to private artifactory
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.8.x"
          python-version: "3.11"
          enable-cache: false #just publish the artifact, nothing to cache
      - run: uv publish
        
